Detail popup window
gabrielcoder247/myportfolio-2 pull request #8
Opened 2021-09-09 13:01 UTC by gabrielcoder247

### `PopUp Window`
**In this milestone**
I and Debas, my partner.
Added the following.

> Html (I added template for popup window)

> Css (I added styles for the popup window)

> Javascript(Debas added Open and close function for the popUp window and I added the evenListener method)

2021-09-09 14:03 UTC, mke2111 requested changes
### Hey @gabrielcoder247, 

**This is a great project you have going on, well-done lad**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-09 14:05 UTC, mke2111 commented on index.html
> +                <br />
- [ ] The modal popup should be populated from the array of objects containing all your projects. Delete this code from the HTML structure.

2021-09-09 14:07 UTC, mke2111 commented on index.html
- [ ] Delete this code pertaining to the projects from the HTML file. Everything related to the project should be populated from the array of objects within the javascript file.

2021-09-09 14:14 UTC, mke2111 commented on popup.js
> +{
- [ ] You are currently having your projects in `projectData` and `projectObj`. It is better to stick to the array of objects i.e. `projectData` to store your project details. It should be from this that you populate all your projects and the modal popup in the HTML file to display your projects. You are using `projectData` for your projects and `projectObj` for part of the modal popup

2021-09-09 14:16 UTC, mke2111 commented on popup.js
> +  projSource.href = projectObj[projId].source;
- [ ] As pointed out in the first comment, populate the modal popup from the array of objects i.e `projectData`.

2021-09-09 17:21 UTC, SpaYco reviewed
Hello 👋,

This is an additional review as a result of the second opinion request.

Populating the page with javascript is part of the project requirement

Check [here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) 👇

> - In order to associate each project with the popup window details, you must use a JavaScript array to store all of the information for all projects.
> 
>   - For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
>   - You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
>   - After that, you could implement the popup window.

Please do the changes then ask for another review

Keep rocking 🚀!

2021-09-10 17:13 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Gabriel Nwachukwu, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-14 11:06 UTC, merged